
from pathlib import Path
import torch
import torch.nn.functional as F
from torchvision import transforms
from PIL import Image
import timm
import json
from .remedy_dict import final_remedy_dict

# -------------------------------
# CONFIG
# -------------------------------
BASE_DIR = Path(__file__).resolve().parent
MODEL_PATH = BASE_DIR / "checkpoints" / "efficientnet_b0_best.pth"
CLASS_MAP_PATH = BASE_DIR / "class_mapping.json"                 # autogenerated mapping
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

IMAGE_SIZE = 224

# -------------------------------
# Load class mapping
# -------------------------------
with open(CLASS_MAP_PATH, "r") as f:
    idx_to_class = json.load(f)

# -------------------------------
# Preprocessing transform
# -------------------------------
infer_transform = transforms.Compose([
    transforms.Resize((IMAGE_SIZE, IMAGE_SIZE)),
    transforms.ToTensor(),
     transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225])
])

# -------------------------------
# Load model
# -------------------------------
num_classes = len(idx_to_class)

model = timm.create_model("efficientnet_b0", pretrained=False, num_classes=num_classes)
state = torch.load(MODEL_PATH, map_location=DEVICE)
model.load_state_dict(state["model_state_dict"])
model.to(DEVICE)
model.eval()

# -------------------------------
# Helper: Get remedy
# -------------------------------
def get_remedy(class_name):
    return final_remedy_dict.get(class_name, final_remedy_dict["_default"])

# -------------------------------
# Predict function
# -------------------------------
def predict(image_path):
    img = Image.open(image_path).convert("RGB")
    img_t = infer_transform(img).unsqueeze(0).to(DEVICE)

    with torch.no_grad():
        logits = model(img_t)
        probs = F.softmax(logits, dim=1)[0]

    conf, pred_idx = torch.max(probs, dim=0)
    class_name = idx_to_class[str(pred_idx.item())]
    confidence = float(conf.item())

    remedy = get_remedy(class_name)

    return {
        "class": class_name,
        "confidence": confidence,
        "remedy": remedy
    }

# -------------------------------
# Example run
# -------------------------------
if __name__ == "__main__":
    test_image = r"D:/vscode/agroai/Backend/ml_models/plant_disease/Cherry leaf (1).jpg"  # change to your test image
    result = predict(test_image)

    print("\nPrediction Result:")
    print(json.dumps(result, indent=4))
